config/routes.rb
Rails.application.routes.draw do

 
  devise_for :admins
  root "home#index"
  get "up" => "rails/health#show", as: :rails_health_check

  # Admin routes
  authenticate :admin do
    root to: "admin#index", as: :admin_root
     end

     namespace :admin, path: "", as: "" do
      resources :categories
    end 
     get "admin" => "admin#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /admin/categories or /admin/categories.json
  def index
    @categories = Category.all
  end

  # GET /admin/categories/1 or /admin/categories/1.json
  def show
  end

  # GET /admin/categories/new
  def new
    @category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories or /admin/categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1 or /admin/categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1 or /admin/categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description, :image)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :authenticate_admin!
  layout 'admin'
    def index
    end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController 
    def index
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= category.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= category.description %>
  </p>
  
  <div class="my-5">
    <strong class="block font-medium mb-1">Image:</strong>
    <%= category.image.present? ? image_tag(category.image) : image_tag("https://via.placeholder.com/50") %> 
  </div>

  <% if action_name != "show" %>
    <%= link_to "Show this category", [:admin, category], class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this category", edit_admin_category_path(category), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/admin/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/categories/index.html.erb
<div class="w-full mt-5">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Categories" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Categories</h1>
    <%= link_to "New category", new_category_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium mt-4" %>
  </div>
 <br>
  <div>
    <table class="w-full table">
      <thead>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Image</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Name</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Description</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Actions</th>
      </thead>

      <tbody>
        <div id="categories" class="min-w-full">
          <% @categories.each do |category| %>
            <%= render category %>
            <p>
              <%= link_to "Show this category", category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
            </p>
          <% end %>
        </div>
      </tbody>

    </table>
  </div>


</div>

app/views/admin/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/categories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @category %>

    <%= link_to "Edit this category", edit_category_path(@category), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this category", @category, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/admin/index.html.erb
<h1>hello admin!</h1>

app/views/home/index.html.erb
   <h1>home</h1>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Violeth Ecommerce" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500">
    <main class="flex ">
      <%= render partial: "shared/header_admin" %>
    <div class="p-5 w-full mt-8">
      <%= yield %>
    </div>

    </main>
  </body>
</html>







        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app_name') %> | <%= t('meta_title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= render partial: "shared/header_user" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_header_admin.html.erb
<nav class="w-64 p-4 h-screen bg-gray-800 sticky top-0 ">
    <div class="flex">
   <%= image_tag("logo.png", class: "w-8 h-8") %>
   <h1 class"text-md py-2 text-white fond-bold hidden md:block">ECOMM ADMIN</h1>
    </div>
    <ul>
        <li>
            <%= link_to admin_path, class: "block px-4 py-2 text-white hover:rounded hover:bg-gray-700" do %>
              <%= icon('fa-solid', 'gauge-high', class: 'mr-2') %> <span class="hidden md:inline-block"><%= t('header_admin.dashboard') %></span>
            <% end %>
          </li>
          <li>
            <%= link_to admin_path, class: "block px-4 py-2 text-white hover:rounded hover:bg-gray-700" do %>
              <%= icon('fa-solid', 'cart-shopping', class: 'mr-2') %> <span class="hidden md:inline-block">Products</span>
            <% end %>
          </li>
          <li>
            <%= link_to admin_path, class: "block px-4 py-2 text-white hover:rounded hover:bg-gray-700" do %>
              <%= icon('fa-solid', 'list', class: 'mr-2') %> <span class="hidden md:inline-block"><%= t('header_admin.categories') %></span>
            <% end %>
          </li>
          <li>
            <%= link_to admin_path, class: "block px-4 py-2 text-white hover:rounded hover:bg-gray-700" do %>
            <%= icon('fa-solid', 'truck-fast', class: 'mr-2') %> <span class="hidden md:inline-block">Orders</span>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, data: { "turbo-method": :delete, "turbo-confirm": "Are you sure you want to sign out?" }, class: "block px-4 py-2 text-white hover:rounded hover:bg-gray-700" do %>
              <%= icon('fa-solid', 'sign-out', class: 'mr-2') %> <span class="hidden md:inline-block">Sign out</span>
            <% end %>
          </li>
    </ul>
</nav>

app/views/shared/_header_user.html.erb
<header>
  <nav class="fixed w-full top-0 bg-gray-600 z-10 py-4">
    <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
      <div class="relative flex items-center justify-between h-16">
        <div class="flex-1 flex items-center justify-center sm:justify-between">
          <div class="hidden sm:flex items-center justify-center">
            <div class="flex space-x-4 font-bold text-3xl">
              <%= link_to 'Store', root_path, class: "text-white hover:underline py-2 rounded-md text-md font-medium" %>
            </div>
          </div>
        
          <div class="flex-shrink-0 flex items-center">
            <%= link_to root_path do %>
              <%= image_tag 'logo.png', class: 'block lg:hidden h-20 w-auto' %>
            <% end %>
          </div> 
          
          <div class="hidden sm:block">
            <%= render partial: 'shared/items' %>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_items.html.erb
<% if admin_signed_in? %>
  <%= link_to 'Edit', '#', class: "mx-2 text-white hover:text-gray-200 font-bold text-xl" %>
  <%#= link_to 'Log out', '#', class: "mx-2 text-white hover:text-gray-200 font-bold text-xl", method: :delete, data: {
    turbo_method: :delete,
    turbo_confirm: 'Are you sure?'
  } %>
<% else %>
    <%= link_to 'Log in', '#', class: "mx-2 text-white hover:text-gray-200 font-bold text-xl" %>
    <%= link_to 'Sign up', '#', class: "mx-2 bg-white text-blue-500 px-4 py-2 rounded-full hover:bg-blue-400 hover:text-white transition duration-300 font-bold" %>
    <% end %>